enable_cache: False

extra:
  tags: zenml-projects

settings:
  docker:
    required_integrations:
      - mlflow
#
#steps:
#  train_model:
#    experiment_tracker: mlflow_tracker
#  evaluation:
#    experiment_tracker: mlflow_tracker