# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model:
  name: breast_cancer_classifier
  license: Apache 2.0
  description: A breast cancer classifier
  tags: ["breast_cancer", "classifier","sgd"]

# Configure the pipeline
parameters:
  model_type: "sgd"  # Choose between xgboost/sgd

steps:
  model_trainer:
    settings:
      step_operator.sagemaker:
        estimator_args: 
          instance_type : ml.m5.large