# environment configuration
settings:
  docker:
    requirements: requirements.txt

model_version:
  name: "peft-lora-zencoder15B-personal-copilot"
  version: production

steps:
  deploy_model_to_hf_hub:
    parameters:
      framework: pytorch
      task: text-generation
      accelerator: gpu
      vendor: aws
      region: us-east-1
      max_replica: 1
      instance_size: xxlarge
      instance_type: g5.12xlarge
      namespace: zenml
