# environment configuration
settings:
  docker:
    requirements: requirements.txt

model_version:
  name: "peft-lora-zencoder15B-personal-copilot"
  version: production

steps:
  deploy_model:
    parameters:
      framework: pytorch
      task: text-generation
      accelerator: gpu
      vendor: aws
      region: us-east-1
      endpoint_type: public
      task: text-generation
      min_replica: 1
      max_replica: 1
      instance_size: 2xlarge
      instance_type: p4de
